expansion:
  uspto:
    - data/uspto_model.onnx
    - data/uspto_templates.csv.gz
  ringbreaker:
    - data/uspto_ringbreaker_model.onnx
    - data/uspto_ringbreaker_templates.csv.gz
filter:
  uspto: data/uspto_filter_model.onnx
stock:
  zinc: data/zinc_stock.hdf5