policy:
  files:
    uspto:
      - aizynthfinder/data/full_uspto_03_05_19_rollout_policy.hdf5
      - aizynthfinder/data/full_uspto_03_05_19_unique_templates.hdf5
stock:
  files:
    zinc: aizynthfinder/data/zinc_stock_17_04_20.hdf5